### ISSUE TITLE
Main site not working properly with ublock

### ISSUE THREAD

**Issue by arj03** [localfoodnodes/localfoodnodes#132]
Ad blockers are very common these days. Visiting the main localfoodnodes doesn't show the map because the following error occurs:

GET https://freegeoip.net/json/?q=85.191.188.32 net::ERR_BLOCKED_BY_CLIENT

This leads to a bad first experience as the map is very important to the frontpage.

**Comment by arj03** [comment]
Would probably be better to use something like this: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation

**Comment by davidajnered** [comment]
Solved in https://github.com/localfoodnodes/localfoodnodes/commit/339eb166769065eafef4cc4b1c9b06769bab54c0

**Comment by arj03** [comment]
Thanks @davidajnered :rocket:
