### ISSUE TITLE
Occational products delivery dates

### ISSUE THREAD

**Issue by zaunders** [localfoodnodes/localfoodnodes#20]
When setting occational production dates, products should not be able to be connected to deliveries before the the first production set. I.e. if 100 pieces are available from June 10, then clicking the delivery on June 2 in the deliveries should not be possible. (Although it is only going to result in there being 0 products available on that date in store)

**Comment by davidajnered** [comment]
Fixed https://github.com/localfoodnodes/localfoodnodes/commit/fc46a83b7c0277c5de016a95b2fb5d811f7d075f
