### ISSUE TITLE
Check out, summa

### ISSUE THREAD

**Issue by albinofsweden** [localfoodnodes/localfoodnodes#41]
Red alert. Varor som anger pris i Kg och Hg får inte räkna samman.
Antinge måste enadast kg pris reps hg pris anges, eller så får det stå "summa anges vid leverans"

Detta är superviktigt fixas snarast.

**Comment by albinofsweden** [comment]
Kritisk....har högsta prio att fixa..

**Comment by davidajnered** [comment]
Fixed
