### ISSUE TITLE
Events in calendar

### ISSUE THREAD

**Issue by zaunders** [localfoodnodes/localfoodnodes#6]
When clicking an event in the node calendar it now filters the shop on that date instead of going to the event

**Comment by davidajnered** [comment]
I'm thinking we could show the event on the node page instead of redirecting the user to the event page. This solution will work even if a delivery date and an event is on the same day.

**Comment by zaunders** [comment]
sounds good, perhaps the event goes on top of the products in that case, otherwise it might get lost  in the end of a long page

**Comment by davidajnered** [comment]
Solved in https://github.com/localfoodnodes/localfoodnodes/commit/365a906b064f792a1544239508c580b2ac003589
