### ISSUE TITLE
Räkna om enhet på varianter

### ISSUE THREAD

**Issue by albinofsweden** [localfoodnodes/localfoodnodes#71]
Byter man enhet på varianter Kg till hg tex, så räknar inte systemet om..Utan slutpriset blir detsamma oavsett.
T.ex. lammlåda för 169 kr/kg som innehåller 10 kg kostar = 1690 kr
Ändrar man till innehållets enhet till hg blir resulatet;
Lammlåda 169 kr/kg som innehåller 10 hg kostar = 1690 kr

**Comment by davidajnered** [comment]
Fixed
