### ISSUE TITLE
Justera veckosaldo individuellt, funkar ej

### ISSUE THREAD

**Issue by albinofsweden** [localfoodnodes/localfoodnodes#79]
Går inte att ändra veckosaldo individuellt på återkommande produkter. Ursprungssiffran kommer tillbaka, och inget sker i butiken när man sparar..

**Comment by davidajnered** [comment]
@albinofsweden Jag provade att ändra ett veckosaldo för dina ägg (lokalt så klart) och det fungerade. Hur får jag det att inte fungera? :)

**Comment by albinofsweden** [comment]
jag menar länken där man justerar varje vecka enskilt....Det funkar inte för mig...
